### ISSUE TITLE
compilation error in NetworkToolkit.cpp

### ISSUE THREAD

**Issue by lupin3rd** [brunoherbelin/vimix#10]
Devuan 3.0 (Debian 10 buster):

[ 76%] Built target GLAD
[ 76%] Building CXX object CMakeFiles/vimix.dir/NetworkToolkit.cpp.o
/home/lupin3rd/repo-git/vimix/NetworkToolkit.cpp: In function 'void add_interface(int, const char*)':
/home/lupin3rd/repo-git/vimix/NetworkToolkit.cpp:97:5: error: 'memset' was not declared in this scope
     memset(&ifreq, 0, sizeof ifreq);
     ^~~~~~
/home/lupin3rd/repo-git/vimix/NetworkToolkit.cpp:97:5: note: 'memset' is defined in header '<cstring>'; did you forget to '#include <cstring>'?
/home/lupin3rd/repo-git/vimix/NetworkToolkit.cpp:20:1:
+#include <cstring>
 
/home/lupin3rd/repo-git/vimix/NetworkToolkit.cpp:97:5:
     memset(&ifreq, 0, sizeof ifreq);
     ^~~~~~
/home/lupin3rd/repo-git/vimix/NetworkToolkit.cpp:98:5: error: 'strncpy' was not declared in this scope
     strncpy(ifreq.ifr_name, name, IFNAMSIZ);
     ^~~~~~~
/home/lupin3rd/repo-git/vimix/NetworkToolkit.cpp:98:5: note: 'strncpy' is defined in header '<cstring>'; did you forget to '#include <cstring>'?
make[2]: *** [CMakeFiles/vimix.dir/build.make:661: CMakeFiles/vimix.dir/NetworkToolkit.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/vimix.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by brunoherbelin** [comment]
Arg! I know I shouldn't have committed large changes before taking vacations :) 
For now, just add
#include <cstring>
at the top of NetworkToolkit.cpp

I'm still working on this feature, which is not fully operational yet. No disruption of the rest of functionnalities.

**Comment by lupin3rd** [comment]
Thank you.

**Comment by lupin3rd** [comment]
Issue closed.
