### ISSUE TITLE
perspective distortion / correction

### ISSUE THREAD

**Issue by MoorPoor** [brunoherbelin/vimix#106]
Hei Bruno!
I haven't been able to test Vimix for a while and I'm really happy about those many options that have been added. 

At the risk that this has already been discussed, are you planning a perspective correction in Geometry F2 mode?

The best thing would probably be something like double-clicking in one of the corners of a source to be able to drag and distort this corner freely. that would open up a huge opportunity for mapping on surfaces!

thanks so much!

![grafik](https://github.com/brunoherbelin/vimix/assets/60827766/52a97812-ced5-4bfd-974a-3a7ee1fb184e)

**Comment by kubriel** [comment]
this is exactly what i was planning to propose.
but we need this also for Displays F5.
anyway thanks for a nice work! vimix is amazing!

**Comment by brunoherbelin** [comment]
okay, I knew this day would come :) 
and I agree this is obviously needed...

It will however take a bit of time as, deep in the rendering pipeline, vimix uses squares for optimized rendering (vertex arrays in opengl); changing for free-form vertices is definitely possible, but i will need to dig a bit (or dive deep, depending on the metaphor)... 

stay tune!

NB: and yes, for Displays view the code behind should be the same so will be transferable

**Comment by brunoherbelin** [comment]
![image](https://github.com/brunoherbelin/vimix/assets/60393189/f7978ad9-5af7-4b8a-ac03-cb66a6f7fce8)


Done! 
(Beta a529b34f99ba1174620aab77bd51425022abdd48 and above, next in Release 0.8.2)
