### ISSUE TITLE
webcam support on linux

### ISSUE THREAD

**Issue by MoorPoor** [brunoherbelin/vimix#11]
Hei!
As corona is now tying us a again more to our desks and video conferences and streaming festivals are going to happen, I wonder how well I can use vimix for that.
I can`t find an option to use a webcam as source but thought you already implemented that?
I'm on ubuntu 20.10

talking about videochat stuff.... a virtual webcam output option is the next thing I`d ultra freaked out about ;)
many greetings!

**Comment by brunoherbelin** [comment]
Yes, vimix supports webcams by adding a source (+) of type 'Connected' : supported devices are listed.
(should already be available in snap channel 'latest/edge')

**Comment by brunoherbelin** [comment]
And yes, I saw how to stream to a v4l2 emulated device (video4linux - drivers for webcams) under linux
But I always try to do the equivalent feature in multiplatform (many users are under OSX) and didn't figure this out yet! 
will come soon..

**Comment by MoorPoor** [comment]
hum...
I tried different webcams and a frame grabber, but still nothing to see under connected devices.
the webcams are old but are working in other applications. 
I just installed the latest edge version

**Comment by MoorPoor** [comment]
Sorry!
I found the problem. Vimix had by default no access privileges to use the camera.
Now its working!
