### ISSUE TITLE
seek OSC message problem

### ISSUE THREAD

**Issue by lupin3rd** [brunoherbelin/vimix#110]
I'm writing a module in Chataigne to communicate by OSC with Vimix... i'm testing all messages and seem that SEEK don't works correctly... i send a float from 0 to 1 but seem that always video run to begin...
I'm using beta branch.

**Comment by brunoherbelin** [comment]
aha..
Before I investigate further, maybe it is a miscommunication in the documentation (https://github.com/brunoherbelin/vimix/wiki/Open-Sound-Control-API) of what the float parameter should indicate : it is a value between 0.0 and 1.0, for the percentage of duration of the video. 

e.g. this instruction :
```
/vimix/current/seek f 0.5
```
will seek to the position at 50% of the total duration (not at 0.5 seconds).

Thanks for confirming this is clear and replicates the bug

**Comment by lupin3rd** [comment]
I followed documentation but if i send 0.5 seek don't go on 50% but at begin... i try to create a video...

**Comment by brunoherbelin** [comment]
ok, then I will check and fix the bug ! sorry for that.

**Comment by lupin3rd** [comment]
https://youtu.be/SCK7jnKc1nI

**Comment by brunoherbelin** [comment]
Please update to Beta f497da79676aeb950360bc2956ef675106d730ff 

It should be fixed! I didn't test extensively but the code was obviously incorrect... 
NB: seek to 1.0 is causing a return to 0 if the source is in loop play mode.

**Comment by brunoherbelin** [comment]
And very cool the module for Chataigne :smile:

**Comment by lupin3rd** [comment]
I confirm that  the problem is fixed! Thank you.

**Comment by lupin3rd** [comment]
I confirm that the problem is fixed! Thank you.

**Comment by brunoherbelin** [comment]
NB: Seek had more hidden problems and I worked a bit on it. 
Thanks for checking that things are still working as expected with Beta cf3bceeb46423e2084369e4f47ae3f09b28dce37

The [OSC documentation](https://github.com/brunoherbelin/vimix/wiki/Open-Sound-Control-API) was also updated; you can see there is a new seek syntax to target a specific time in HH:MM:SS format
