### ISSUE TITLE
Luma key white

### ISSUE THREAD

**Issue by MoorPoor** [brunoherbelin/vimix#113]
As far as I can tell, it's quite difficult to key white from a source.
Lumakey removes black well, but there is no option for white.
I couldn't get any good results under Chromykey either.
I think another threshold for bright parts should be added at Lumakey.
What do you think?

this is how Lumakey is solved in OBS - just as an example  
(Video background is white)
![Bildschirmfoto vom 2023-11-17 18-42-50](https://github.com/brunoherbelin/vimix/assets/60827766/7f2c85fe-5128-455e-8460-7595233362d7)

**Comment by brunoherbelin** [comment]
Thanks for the suggestion!

I added a 'Luminance' parameter to the Lumakey filter: white lumakey with Luminance = 1.0

If you try version Beta 657b05d077a480a1fc89dada6af6b56905c6c211, you can access the new parameter;
![image](https://github.com/brunoherbelin/vimix/assets/60393189/b532b10a-5b29-4829-80fe-5826cfdaa5cb)


Alternatively, you can create a custom filter with the following code:
```
void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
    float Luminance = 1.0;
    float Threshold = 0.5;
    float Tolerance = 0.5;

    vec2 fragPos =  fragCoord.xy / iResolution.xy;
    vec3 RGB = texture(iChannel0, fragPos).rgb;
    float L = dot(RGB, vec3(0.299, 0.587, 0.114));

    fragColor = vec4( RGB, smoothstep( Threshold, Threshold + Tolerance * Tolerance, abs(Luminance - L) ) );
}
```

**Comment by MoorPoor** [comment]
thanks.
works great so far!
![grafik](https://github.com/brunoherbelin/vimix/assets/60827766/fde41be2-fc02-4b91-8608-e6f432d0ebcc)

**Comment by MoorPoor** [comment]
I checked the beta with alpha key now. 
works perfectly as far as I can tell

**Comment by brunoherbelin** [comment]
NB: see #117 for update (bug fix)
