### ISSUE TITLE
Error message death loop

### ISSUE THREAD

**Issue by MoorPoor** [brunoherbelin/vimix#114]
Hello, I wanted to apply a blur filter to a moving ball... the error message that came up now paralyzes everything and cannot be removed.

For now I'm going to reinstall Vimix, but how would I normally go about it if this isn't an option? It should still be possible to close such endless error messages.

However, I don't know what the error itself has to say ;)
I`m runing ubuntu 23.10 with nvidia GPU
![Bildschirmfoto vom 2023-11-30 17-26-54](https://github.com/brunoherbelin/vimix/assets/60827766/bc6e7acc-0e4e-4de6-8464-75d675872486)

**Comment by brunoherbelin** [comment]
Should be fixed now (Beta >= abdc70121d857f57f98d98d026adb9be4a69dcfd)
