### ISSUE TITLE
seek OSC message behavior

### ISSUE THREAD

**Issue by lupin3rd** [brunoherbelin/vimix#120]
I think that seek message must "move" clip only on active parts.
Actually if i cut some video segment on media player and try to use seek message from 0 to 1 if i send numeric message that is inside the cut segment vimix play always the begin of active video... i think that 0 to 1 must be only the not cutted video segment.

**Comment by brunoherbelin** [comment]
I see, but what would you suggest when video has multiple segments?

![image](https://github.com/brunoherbelin/vimix/assets/60393189/ed9224aa-be91-472d-b493-58767485e96e)

According to what you suggest, the [0..1] target should consider the % of the playable accumulated segment?
Or the seek command should specify the % and the index of the segment (e.g. seek(1, 0.5) for 50% of segment 1) ?

**Comment by lupin3rd** [comment]
> According to what you suggest, the [0..1] target should consider the % of the playable accumulated segment?

Yes. I suggest this solution. But...
> Or the seek command should specify the % and the index of the segment (e.g. seek(1, 0.5) for 50% of segment 1) ?

...also this solution is very interesting. You could implement both solution?
seek(0, X.X) the % playable of all segments
seek(1, X.X), seek(2, X.X) the % of single segment

**Comment by brunoherbelin** [comment]
Thanks!. OSC seek with percent is now behaving as expected, i.e. the target [0..1] seeks to a % of the actual playing segments (discarding cut segments). API documentation updated.

Please try Beta 842247de547ec98391853500fa2be2002e268995 and let me know : it seems to work for me, but maybe there are still problems..

**Comment by lupin3rd** [comment]
I confirm that now seek works only with playing segments. No problem... i try a lot with random OSC messages.
