### ISSUE TITLE
autoadaptive interface for small screen but high resolution!

### ISSUE THREAD

**Issue by MoorPoor** [brunoherbelin/vimix#121]
Hei Bruno!
special problem: very small screen but very high resolution! 2560x1600 @ 10" 

I `m writing for a friend as his experience with vimix stopped more or less after opening the Programm, as he is not able to scale the menu right. I guided him once, but with time or update it changed again.
For a new user, this is already a dramatic exclusion criterion :(

This is certainly a very special case, due to the extremely high screen resolution and very small display. 
a solution would still be helpful.

is there a way of somehow scale the interface according to the screen resolution? so that at least someone can see something and then adapt it to their own taste later?

he is using ubuntu 23.10 with 200% scaling screen setting but vimix seems to ignore this setting.

![photo_2024-01-22_09-44-13](https://github.com/brunoherbelin/vimix/assets/60827766/577d6f46-851d-4115-90d4-a40f4dc6dc14)

**Comment by brunoherbelin** [comment]
And I forgot to suggest the following temporary hack to help see something in vimix until the bug is fixed:

Open the file `~/.config/vimix/vimix.xml `

Find the line setting the `Application` parameters;

```
<Application scale="1" accent_color="2" smooth_transition="true" save_snapshot="false" action_history_follow_view="false" show_tooptips="true" accept_connections="false" pannel_main_mode="0" pannel_playlist_mode="1" pannel_history_mode="0" pannel_always_visible="false" stream_protocol="0" broadcast_port="7070" loopback_camera="0" shm_socket_path="" accept_audio="false"/>
```

Change `scale` to a larger value, e.g. `<Application scale="10"`

**Comment by MoorPoor** [comment]
thanks for your response.

his resolution is 2560x1600 @ 10"
but I would ask you to pause this issue for now, as he managed to adjust the scale factor and is happy for now. vimix and ubunut keeps the setting now, so no need to investigate further.
Why it did not adjust well initially - I don`t know, but as this is such a special device and case, lets skip that as I have no access to that device.

sorry, for bothering you!

**Comment by brunoherbelin** [comment]
Okay, thanks for letting me know.

FYI, with this  resolution on a 10 inches diagonal monitor, vimix would estimate the base font size at 47 pixels (for a 4mm height text). That is, if GLFW would provide the monitor size information. Therefore, as this is not the case, I conclude the problem is when GLFW cannot provide monitor size (i.e. here vimix sets font size to 20 pixels, i.e. ~1.5 mm font height, which could correspond to what your screenshot shows). 

This shows that it can happen and vimix should have a way to prevent this.  I will investigate for future versions.

**Comment by brunoherbelin** [comment]
I didn't find a general bugfix but increased the default font height and allowed larger scaling in Beta 5a077d2f52e65a29cc350e853be1aa662d3c1851 

Hope it helps

**Comment by brunoherbelin** [comment]
Please try with Beta 47ff1a2dd8aea954e7de13838d91fc80f5bdc8df to launch vimix with command line and adding the argument `--fontsize` and a value:

    vimix --fontsize 50

This will enforce a user-defined font size and should resolve this issue.
