### ISSUE TITLE
Output window problem

### ISSUE THREAD

**Issue by lupin3rd** [brunoherbelin/vimix#126]
Sometimes seem that output window lose the setting.
I don't know if the problem could be due to a small loss of communication with the secondary screen (HDMI), but it seems that the output window suddenly returns to the primary screen.
Although, as you can see from the image, on vimix the setting is that it must be fullscreen on the screen connected with HDMI.

Vimix remember the setting but output window go in the primary screen.
![Screenshot_2024-02-21_19-58-40](https://github.com/brunoherbelin/vimix/assets/1455316/4a793ee6-89cc-4b33-a366-e3dd6bdb93fa)

**Comment by brunoherbelin** [comment]
I couldn't replicate: what event seems to cause the change ? unplug monitor? 
Is there an action from the session window manager (Gnome or Kde?)  ?
And even so, vimix is testing windows at each update... 

Thanks for providing more contextual info for replicating.

**Comment by lupin3rd** [comment]
I can't replicate... it happens sometimes in my show... i think that can be a problem of my secondary monitor (projector).
Seem an unplug, it lacks connection... and after 1 sec it reconnect...
Output window go in the primary screen but in display configuration (F5) vimix show that configuration is "fullscreen on display" (see screenshot). I need to reclick on this setting.

**Comment by brunoherbelin** [comment]
What should we do with this issue? I could try to play with unplugging / replugging a monitor to test?

**Comment by lupin3rd** [comment]
I solved my problem by purchasing an HDMI cable with better shielding, now I have no signal loss.
However, Vimix's behavior with output management should be improved.
As you can see from the test I attach with the manual detachment of the cable, Vimix remains with the active setting "fullscreen on display 1" but in reality the output window is not positioned as we see it in the vimix output.
I do a lot of test, sometimes option go on "window" and the output window return on primary monitor (which logically would seem to be the most normal behavior if the second monitor is disconnected).
I think that more options could be useful to manage the output, such as being able to save a setting based on the monitor/projector that is connected. Something like "force fullscreen when is attached ProjectorModelNumber".
In this way Vimix can solve automatically a disconnection problem.

https://github.com/brunoherbelin/vimix/assets/1455316/6c186758-21d2-4260-92cb-f82f3ef4c045

**Comment by zcbernard** [comment]
Hi,  I'm using ubuntu 23.10. I sometimes had this problem which I resolved (never found since) by reversing the physical position of the screens in the Ubuntu control panel.
If that helps!
Bernard

**Comment by brunoherbelin** [comment]
Hi there ! Following up on this issue, I made a bugfix in Beta c2b7892e6c8debdd283574249cb1ac084feebe91 which I hope fixes the problem encountered here.  However I could not try as I had drivers issues with my Ubuntu nvidia, and stopped testing with un-plugging & re-plugging the external monitor many times as it ended up crashing my machine! I might have to report a bug to Ubuntu :wink: !!

Thanks for testing on your side and letting me know if the bug seems fixed !

**Comment by lupin3rd** [comment]
Hi Bruno, i think the bug is not fixed. I attach a video of a test.
As you can see if I set fullscreen in monitor 1 and then disable fullscreen, vimix behaves correctly and returns the output to the previous mode (window mode on monitor 2)... but if I disconnect while in fullscreen mode the monitor 1 behaves strangely , makes fullscreen in monitor 2.
The normal behavior should have been to go back to window mode.
Then if I reconnect monitor 1 at this point I would expect the output to return to fullscreen mode on monitor 1, but instead nothing happens.

https://github.com/brunoherbelin/vimix/assets/1455316/e08fa25d-b37f-451d-b7b9-7613808d9b5b

**Comment by brunoherbelin** [comment]
Thanks for your feedback. It tried to be too smart and it failed :wink: ..

Latest Beta 7ca6299fba6a9d756471cdf7e41f23d0ec885a84 should less subtle but more reliable: all windows exit full-screen on monitor disconnect.
