### ISSUE TITLE
Application closes suddenly

### ISSUE THREAD

**Issue by zcbernard** [brunoherbelin/vimix#130]
Hello, I am using Vimix on ubuntu 23.10 and acer nitro 5 AN515-42. Everything works perfectly except when I accidentally delete a file in the session (jpeg, png, mov...) assigned to a keyboard key. If I press the keyboard key the application closes immediately. Can this be corrected? For example, deleting a file deletes its assignment(s). Otherwise, for your information, I use a Sony PS2 pad to control the keyboard via Antimicrox (ubuntu repositories). Finally, thank you for this superb work. Good day
Bernard

**Comment by brunoherbelin** [comment]
Thanks a lot! This was indeed a nasty bug :smiling_imp: 

Hopefully it was easily fixed in Beta 25be63ef2c4c3d6c345d0082af9dfbb5491038fc
When deleting a source, now the associated input callbacks are removed.

For now, you need to [compile vimix from source on Beta branch](https://github.com/brunoherbelin/vimix?tab=readme-ov-file#try-the-beta-branch) : it would be great if you could try and confirm the bug is fixed!

**Comment by brunoherbelin** [comment]
> I use a Sony PS2 pad to control the keyboard via Antimicrox (ubuntu repositories). 

Thanks for the tip! I didn't know this software, and it does the job to map any joystick input !! 
I still need to [write the documentation for the input mapping](https://github.com/brunoherbelin/vimix/wiki/Advanced-features) ... That would be a good place to mention this !

**Comment by zcbernard** [comment]
Hello, thank you for your answers. I will try to compile it will be a first for me. We learn something every day! I sometimes also have the same bug (Vimix frozen after 2/3 session load #122) but very rarely and on large sessions.
So I'm going to try these tricks otherwise I'll wait for version 0.82XX ;-).
As for the Sony Pad, with a Sony to USB connector adapter you can connect 4 pads without any problem. This allows for very instructive group image construction games.
Bernard

**Comment by brunoherbelin** [comment]
> Done, everything fine ! Many thanks p-)) Bernard

Great, then closing the issue !

> This allows for very instructive group image construction games. 

Exciting! Interesting idea, and glad to welcome more suggestions in that direction!
As you have observed, **vimix** tries to be an alternative to the classic view of how video mixing ('VJ-ing') is done: collective mixing seems fun :smiley:

**Comment by zcbernard** [comment]
Good evening,
actually it's the work table aspect on which we throw images and videos
that I liked, already with glmixer.
If you agree, I will prepare some videos presenting the use of the Sony
pad, and the first simple games for constructing images with vimix.
A tool that can be diverted from its primary function is a good tool.
In my eyes this is the case for vimix, as was the case for turntables and
DJs, or even before Pierre Schaeffer and the broken record or the closed
groove.
Creation almost always involves diversion.
Have a good evening
Bernard
