### ISSUE TITLE
Small bug with sound

### ISSUE THREAD

**Issue by zcbernard** [brunoherbelin/vimix#138]
Bonjour, 
Small bug with the sound it seems to me. The video (https://youtu.be/xdGZY3fYUvs) is the recording of the sequence of two video with sound sessions. The first mainly consists of low-pitched sounds, the second includes fine, high-pitched sounds. As soon as the sequence is prepared, the sounds of the second mix with those of the first. In the video the setup of the second session is at 19". Is it possible to correct this? That would be great

Bonne journée
Zcbernard

**Comment by brunoherbelin** [comment]
Humm, not sure to understand the problem; let me know if this is the situation you have:

 - you have two vimix session files, each have different video and audio
 - you trigger the smooth transition from session 1 to session 2 
 - you expect that the volume of the sessions fades in (for session 2) and out (for session 1) at the same time that the transition is done between sessions

I indeed did not work on the transition of audio between sessions. I guess this should be possible... I will investigate.

If this is not the bug you describe, thanks for giving more info!

**Comment by brunoherbelin** [comment]
Ok thanks! Bug challenge accepted... 
Will post an update here when done.

**Comment by zcbernard** [comment]
0,8 d...  perfect

**Comment by zcbernard** [comment]
It's running perfect.
many thanks
zcbernard

**Comment by brunoherbelin** [comment]
Great! 

Also I am working on a better integration of audio. Since Beta 628250030584fc7cf91cda2cf2c3e60776480a8d, the transition view is now fading-in the volume of the sources inside the session as it is faded in. The control of general output opacity is also affecting the general volume.

i still don't want to emphasize too much the audio features as there are lots of features musicians would then start to require ... :wink:

**Comment by zcbernard** [comment]
Bonjour ,
thank you for fixing this little bug. I agree with you, we should not
advance too far in the development of audio. Vimix would become a gas
factory. As is, it is very good. By using sound videos without images, i
can even do audio mixing ( ;-)). For my part, I am doing control tests
using both the mouse, gamepad and a tablet with OSCTouch. The three
complement each other well.
Bonne journée
Zcbernard

**Comment by brunoherbelin** [comment]
Update on Audio: recording of video AND audio should now be quite operational. Since commit 19b8412d67ff5ab7575bd7eb07cb93ad163f23d2, the pause/unpause of recording also works when capturing audio. 

Until further request, I will leave it as is...

**Comment by zcbernard** [comment]
👍👍
