### ISSUE TITLE
some generators are not working

### ISSUE THREAD

**Issue by MoorPoor** [brunoherbelin/vimix#14]
Good morning!
I just wanted to let you know, that some of the generated patterns are giving me errors 
(Timer, Clock, Blob and Lissajous)
I`m using the snap --edge version on Ubuntu 20.10
![Bildschirmfoto von 2020-12-09 10-46-17](https://user-images.githubusercontent.com/60827766/101613803-790f5a80-3a0c-11eb-88b7-2863c55755be.png)
greetings!

**Comment by brunoherbelin** [comment]
Arg! I knew this would come :( !  This is the risk of using 'bad' or 'dirty' plugins from gstreamer; they are not always available, depending on versions on the system...

I'll try to force the snap to compile with the good version.

But to be more forward-looking: these patterns will be replaced by GPU generators (i.e. shadertoy code), and will probably be obsolete at some point.

**Comment by MoorPoor** [comment]
perfect! so don't stress yourself with correcting that.

**Comment by brunoherbelin** [comment]
I quickly investigated: indeed the snap uses an old version of gstreamer which does not have these plugins. A temporary patch is done to remove those generators from the list. 

I am waiting for [snapcraft](https://snapcraft.io) to release the Gnome environment on the Core 20 (which would then include more up to date libraries and a more recent gstreamer) as this will solve the issue. They unfortunately didn't give a date for this update.

As agreed, this is not a so critical problem to require to entirely change the snap to recompile the gstreamer library (which is huge and has tons of dependencies).

**Comment by DarrellJonsson** [comment]
Using Ubuntu 19.10 and Mac OS 11.4 a similar error when loading Generated media..using Snap on Ubuntu and DMG for Mac.

*** Would compiling the code on Ubuntu 19.10 or Mac Big Sur correct this issue?

* Would loading the app from  more recent Ubuntu or Mac OS resolve this?** 

_Generated Media -- Warning - Stream 635777673255589724 Could not construct pipeline frei0r-src-lissajous0r ratiox=0.001 ratioy=0.999 ! videoconvert ! appsink name=sink:_

**Comment by brunoherbelin** [comment]
Hi 

So tackled the issue in two ways:

 * Snap under Linux now finds the gstreamer plugins, and I could thus add more generators
 * vimix (all OS) now tests the availability of the gstreamer plugin before offering the generator to the user (i.e. if not available, the lissajous generator will not be in the list)

The update is operational on snap Linux, and will soon be next release on OSX

thanks for the feedback!
