### ISSUE TITLE
Segmentation fault with Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by lupin3rd** [brunoherbelin/vimix#141]
I compiled Vimix with new Ubuntu 24.04 LTS. When i try to run vimix the result is: Segmentation fault (core dumped).
I attach the strace result.
[output.txt](https://github.com/brunoherbelin/vimix/files/15143927/output.txt)

**Comment by brunoherbelin** [comment]
Thanks for letting me know (not yet upgraded to 24.04); will try soon!

The flatpak and snap are up to date with the source version, so should be compatible with your work.
Can you confirm the packages are working?

**Comment by lupin3rd** [comment]
> Thanks for letting me know (not yet upgraded to 24.04); will try soon!
> 
> The flatpak and snap are up to date with the source version, so should be compatible with your work. Can you confirm the packages are working?

I try the flatpak package and all works fine in Ubuntu 24.04. I don't test yet snap package.

**Comment by zcbernard** [comment]
As far as I'm concerned, the snap version of vimix works with ubuntu 24.04.
zcbernard

**Comment by brunoherbelin** [comment]
Here you go ! I finally got time to upgrade to 24.04 and could replicate the problem and fix it. I hope it was all.

Thanks for checking Beta 2d99870ec2d3171a00dbcb045bb8dca629caee60 and confirming: if it works I will also merge in Main branch as it is a vital fix.

**Comment by lupin3rd** [comment]
I confirm that new beta solve the problem. Thank you.

**Comment by brunoherbelin** [comment]
Great !! :+1: 
Thanks lupin!!
