### ISSUE TITLE
Wifi et paramètres

### ISSUE THREAD

**Issue by zcbernard** [brunoherbelin/vimix#144]
Good morning,
A problem when using Vimix offline. Wifi disabled, opening the settings crashes the application which closes. Wifi activated no problem.
Good day
zcnbbernard

https://github.com/brunoherbelin/vimix/assets/162862049/cf3d1791-6426-4a19-8dd9-1bf526d6aa26

**Comment by zcbernard** [comment]
Hello
From the last release evrything works fine, even without internet access.
Have a good day
B

**Comment by brunoherbelin** [comment]
Thanks! And sorry I didn't reply earlier. Good that the problem is resolved.

**Comment by zcbernard** [comment]
No problem. It was a very little bug.
B
