### ISSUE TITLE
Playback speed on first run after opening a session

### ISSUE THREAD

**Issue by ThomZenTury** [brunoherbelin/vimix#148]
Hi again!

I am just wondering if there is a specific reason for the playback speed of a clip to be "1.0" (=100%) on the first run after opening a session for the first time of the day although it was saved with a different value. The speed indicator in the player window shows the correct value that was saved the last time, but the actual movement is surely 100%.

Current setup:
System: Ubuntu Studio / Kubuntu 22.04.04 / 6.2.0-1017-lowlatency
CPU: Intel i7-10750H (12) @ 5.000GHz
GPU: NVIDIA GeForce RTX 2060 Mobile 
Vimix 0.8.2d-28-g94fbe58

Have a nice day!

**Comment by brunoherbelin** [comment]
Nice bug hunting ! 🐛 
This is definitely something that should be fixed. 
I will let you know when done.

**Comment by brunoherbelin** [comment]
Should be fixed in beta 02c69c1686df879c3b000f7e058d113ba922c60e

**Comment by ThomZenTury** [comment]
Hi @brunoherbelin!

I just compiled the beta 0.8.2d-54-gd22e239 and it works as expected. Playback speed o first run is just as it was saved in the session.

Thank you so much for your time and efforts!

Have a nice weekend!
