### ISSUE TITLE
Sound and video

### ISSUE THREAD

**Issue by zcbernard** [brunoherbelin/vimix#151]
Hello,
Probably a bug. I use short video files (.mov) with sound and image. The attached video shows the problem. I install a file in vimix, without activating the sound. Everything is fine. I close and reopen vimix everything is OK, I find my file and its projection. I activate the sound, everything still works. If I close and reopen vimix the image has disappeared from the screen (display), while it is still visible in the player.
What do you think?
Best regards
Bernard

https://github.com/user-attachments/assets/9eb9a732-cf27-4695-a4bd-0198d5aaf072

**Comment by brunoherbelin** [comment]
Thanks for this bug report! It went under my radar :wink: 

It should be fixed with Beta commit e6d21518d231f48f15e62f4d86bb01dd48818fc1

**Comment by zcbernard** [comment]
Hello,
i will try this version quickly
cordially

bernard
