### ISSUE TITLE
Maybe Request? OSC commands for changing "Blending" modes

### ISSUE THREAD

**Issue by ThomZenTury** [brunoherbelin/vimix#155]
Dear Bruno!
I spent a bit time to create an OpenStageControl Interface like announced and I am slowly preparing to offer it here as a template for everyone interested.

I stumbled across three issues and for the sake of keeping things tidy I will open a new issue for each.

1st one would be that I couldn't find any OSC commands in the API for changing the "blending" mode on a clip (normal, screen, multiply etc.). Am I just a bit blind or is it not available at the moment? And if not would it be possible to implement this?

The fun when using Vimix doesn't stop. Still using it in high appreciation.

Have a nice day!

**Comment by brunoherbelin** [comment]
Added in Beta commit 4e813c2540c1b7bf346b982723d4753dcdfafe3b

**Comment by brunoherbelin** [comment]
Accepted OSC messages formats : 

    /vimix/#0/blending s 'hard light'


or

     /vimix/#0/blending i 2


where the string is the same as in the UI menu, and the integer argument is between 0 and 7 (index in the list of blending modes)

**Comment by ThomZenTury** [comment]
How a day should start!

Whether you did a night shift or you are overseas - thank you so much!
It's already implemented in the OSC template and if testing goes well the next few hours I will put it out including instructional video. Can't wait any more...

Have a nice day!

**Comment by brunoherbelin** [comment]
Minor update, for consistency with the [vimix OSC API ](https://github.com/brunoherbelin/vimix/wiki/Open-Sound-Control-API), where all arguments should be `float` for uniformity and simplicity, I changed the argument to be `f` instead of `i`. This is documented in the API wiki. 

Should be good to go! closing this.
