### ISSUE TITLE
Issue: OSC sync command seems to not return negative alpha values

### ISSUE THREAD

**Issue by ThomZenTury** [brunoherbelin/vimix#157]
And the last one...

When trying to sync the OpenStageControl Interface with Vimix sent back information it seems that the alpha values are not returning negative values even if they are in the "Deactivated" area of the circle.
First, I thought it is an OpenStageControl restriction but looking at the values with OSCdump in a Terminal tells me different. A should-be-negative value is sent back as "0.0000".

It's not a biggy but would maybe more accurate.

I hope these observations and requests are not too much.

In any way I wish you a fabulous week!

**Comment by brunoherbelin** [comment]
haha... this might be indeed a remain of a previous implementation where I was clamping alpha to [0 1].
I will investigate

And no, its good to keep asking to making vimix better! I am very much looking forward to the Open Stage control UI !

**Comment by brunoherbelin** [comment]
Should be fixed in Beta commit 4d9063f16cbda79ccc8df8a39b4de87ff24708e0

**Comment by ThomZenTury** [comment]
Nearly perfect!
But since I still love and use the "batch" feature ( that you kindly implemented a few months ago ) I just realized that the values in these returning batch arrays are still put to "0.0" when they should be negative.
Otherwise adequately working! Thanks!

**Comment by brunoherbelin** [comment]
Devils lies in the details indeed ! :smiling_imp: 
Updated in Beta commit d273a7fcb450eb597d3f7de1b5566332338f5cb2 !

**Comment by ThomZenTury** [comment]
Tell me about it!
I would love to have your speed and awareness when it comes to debugging.
Works perfectly now!
Thank you so much!
