### ISSUE TITLE
Transition from one session to an another

### ISSUE THREAD

**Issue by zcbernard** [brunoherbelin/vimix#158]
Hello,
A problem with the transition from one session to another.
I do a fade to black to end a session, I want to open another session, once this one is selected in "pre-opening" the fade to black disappears and the previous session becomes visible again.
A possible solution?
In any case, thank you for all this development work.
Sincerely
Bernard
https://github.com/user-attachments/assets/ae09a26a-2059-48df-add2-01d8e0874fe4

**Comment by brunoherbelin** [comment]
Nice catch ! This is not a bug per-se, but it needs an improvement of behavior to avoid the misunderstanding.

**The solution**: switch the transition fading mode to 'Fade to black'. It will then work as expected.

**The problem behind** : cross fading a new session with the current session means mixing the two colors, so starting a cross fading indeed starts with the current session visible and mixes the new one on top of it.  In practice, the cross fading transition loads the new session and puts it in the current session as as 'Session Source' (the two sessions are thus visible), moving it to the mixing view to bring it to the center. You can see this if you press 'Cancel' in the Transition view . 

**The possible options**

1. Keep the output fading to the value manually set by user in mixing circle : the behavior after you set to black the fading will be that the output will remain black during the whole transition and user will have to manually fade back to visible.
2. Automatically detect that there is a fading to black (manually set by user) and switch to Transition 'Fade to black' 

I would be in favor of option 2. If you confirm i will implement this behavior. 
Or you have a third option in mind?

**Comment by zcbernard** [comment]
Hello,
I would say that solution 2 is fine. But to add a little difficulty, would it be possible when saving a session (manually or automatically when closing it) to save the fade to black position. So: we "fade to black" the first session, we preload the second (the first remains fade to black) and the second opens as it was saved, with or without fade in. This would allow fade to black and fade in or close to black and "cut" opening. And vice versa ;-))

many thanks
bernard

**Comment by zcbernard** [comment]
![picture_01](https://github.com/user-attachments/assets/1a6670d8-4b8d-4c92-98ce-a543cd7fcaa6)
