### ISSUE TITLE
Issue: uniform naming and thier default values?

### ISSUE THREAD

**Issue by ThomZenTury** [brunoherbelin/vimix#159]
Oh, ok, just two more that were hidden on my list concerning shader names and their default values.
I don't know if these are shader or Vimix restrictions. 

1. Uniform naming - no numbers allowed?
It seems that numbers / digits are not allowed in uniform names.
When writing a shader to Vimix's "Shader Editor" the uniform's slider do not show up in the GUI if they carry names like 
`uniform float xposition1` 
where 
`xposition (without the number)` 
is totally fine and working, i.e. the shader works fine but the control slider does not show.

2. Default values - decimal limit
If I give a default value to a uniform the control slider only shows up if there is not more than one decimal value.
```
uniform float xposition = 0.2 // slider showing
uniform float xposition = 0.25 // slider not showing
```

Once more I am very happy about your mindset about bugs/issues/questions.

Have a nice day!

**Comment by brunoherbelin** [comment]
Thanks ! 
Should be fixed in Beta commit 136b1561c189fe080e87f4182b1aec54509af167

Variable names now must start with a letter, but then can contain letters, numbers and underscores ('_').

**Comment by ThomZenTury** [comment]
Perfect monday entry!
Yes, this is solved and working!
Thanks a lot!

**Comment by brunoherbelin** [comment]
Good to hear! Emjoy!
