### ISSUE TITLE
New features request

### ISSUE THREAD

**Issue by OlegoroV** [brunoherbelin/vimix#16]
Can You please add workspaces like in GLMixer?

And I cannot find where to choose Monitor for Output window. Is this option exist? If not, can You make it?

**Comment by lukors** [comment]
> And I cannot find where to choose Monitor for Output window. Is this option exist? If not, can You make it?

Solution from #3: There should be an output window when you start the program, it might be behind the Vimix window. Drag that window to the monitor you want to output to and double-click it to maximize it there.

**Comment by brunoherbelin** [comment]
Hey Oleg!

**Monitor selection**: as lukors says, the control of output is directly on the output window itself: I want to minimize control panels and preference windows, but as you are not the only one to ask, maybe something more explicit is needed: would it help to add a contextual menu (right clic) in the output window? (with actions 'fullscreen' and select monitor) 

**Workspaces**: I'm not sure I want to add the same as in GLMixer. For vimix, I want to focus on an interface to manipulate the objects directly (instead of buttons and GUI windows).
The first alternative in vimix is to include a session as a source (drop a .mix file): this allows grouping objects and hiding the multiple sources inside it. 
Another alternative which I could think of would be to make better use of the layers view: maybe add 'backgroud' and 'foreground' dedicated areas? How would you imagine it?

Let's work on a nice, clean and hands-on interface!

**Comment by OlegoroV** [comment]
Hello, Bruno!

Monitor selection: well ok, I can use just drag'n'dropping Output window.

Workspaces: drop a .mix file is a cool feature, but how to control sources inside it?
Often I need dozens of sources and old workspaces were perfect solution! And they use minimum of interface space. But Your suggetion to add separate areas for background and foreground sources is also wonderful idea. But not instead of workspaces =)
Maybe instead of workspaces there can be some pool of sources?

**Comment by brunoherbelin** [comment]
Please try latest/edge v0.5 : there is a first draft of the layer's foreground and background locked sources. 
We might want to find better use and ways to display and control this: feedback welcome.

Pool of sources and/or workspaces: yeah, i'm working on something...

**Comment by OlegoroV** [comment]
Yes, new areas for background and foreground layers in Layers view is a good idea! Thank You!
Can You, please, make visibility of theese areas toggleable in Mixing view?

**Comment by brunoherbelin** [comment]
Ha, I see, user could select if loked sources are visible (although locked) or completely hidden. That makes sense. This would then apply for both mixing and geometry view. 

- if visible, a locked source is shown disabled, but editable only if user uses [CTRL]+mouse (like currently in Mixing view)
- if not visible, a locked source is not editable (no frame at all, like currently in Geometry view)

I will add this in the Layers view : user will be able to toggle 'show'/'hide' next to the background and foreground areas.

Thanks for the suggestion of improvement!

**Comment by brunoherbelin** [comment]
Hi There, Please try the latest/edge version 0.5. 
These features are now more mature:
- lock/unlock protects a source from mouse actions. Can be locked/unlocked from icon on source directly, anytime
- 3 workspaces: background, stage and foreground, as distributed in layers view. The mixing view now allows selecting which workspace to display

This will be complemented with the group/ungroup feature.

**Comment by linuxnow** [comment]
>     * 3 workspaces: background, stage and foreground, as distributed in layers view. The mixing view now allows selecting which workspace to display

I can't see how to make one layer active. I.e. I'd like to see what's in the background layer instead of the stage, to make a quick switch.

**Comment by brunoherbelin** [comment]
Sorry for typo, it should read " The GEOMETRY view now allows selecting which workspace to display" 

In short: 

- put the source in background, stage or foreground in LAYER view
- select which workspace (background, stage or foreground) to work on in GEOMETRY view
- all other views are not affected.

The main need is to avoid the superposition of many sources in geometry manipulation (which becomes quickly overcrowded as sources are often with the same dimension). But for MIXING, the transparency is always free to change, as changing the visibility of a source in BG or FG would not be related to its place. And obviously, TEXTURING view is not affected.

**Comment by OlegoroV** [comment]
Hiding FG and BG layers in MIXING view would be also helpful for my purposes.

**Comment by brunoherbelin** [comment]
A more general solution could be to allow hiding the locked sources : would this answer your need?
