### ISSUE TITLE
Window and Monitor management

### ISSUE THREAD

**Issue by brunoherbelin** [brunoherbelin/vimix#18]
Known issues to be fixed with [glfw](https://www.glfw.org/):
- moving window between monitors is not detected; display should update opengl context and change resolution of display
- provide an option for software FPS limitation; when system does not enable v-sync, vimix should try to limit update to 60Hz
- fullscreen of output window: a context menu could help select the target fullscreen monitor

**Comment by linuxnow** [comment]
Just a quick question: can window decorations be removed from the output window? Like when you press 'f" in video players for full screen.It could be the shortcut to maximize the output window.

**Comment by brunoherbelin** [comment]
All this should be fixed since v0.8.1
