### ISSUE TITLE
Turning on vsync removes frame limiter

### ISSUE THREAD

**Issue by lukors** [brunoherbelin/vimix#19]
Compiled from commit afc0c7a.

## Repro steps
1. Turn on the program while vsync is turned off
2. Turn on vsync

## Result
The framerate counter is immediately increased to its limit, for me ~300 fps.

## Expected
When vsync is turned on I would expect the framerate to stay software-limited until the program is restarted and vsync is activated.

**Comment by brunoherbelin** [comment]
The user selection for vsync was removed : vsync is enabled by default if possible, and if not framerate limiter ensures fps does not exceeds 62 fps.
