### ISSUE TITLE
How do I change the text size of the interface?

### ISSUE THREAD

**Issue by DarrellJonsson** [brunoherbelin/vimix#2]
The default text is too small on my monitor. 
How do I change the text size of the interface?

**Comment by MoorPoor** [comment]
the top left "burger" menu gives you an option to scale under Appearance

**Comment by brunoherbelin** [comment]
Thanks!
I'll check why it is that small under this screen resolution 
(its supposed to be calculated to be proportional to screen size, not resolution, but apparently not working :) )

**Comment by MoorPoor** [comment]
the interface scales nicely now, thanks!
it seems a bit blurry, though, but I don't care.

**Comment by brunoherbelin** [comment]
Bug fixed! 
I could reproduce the issue; and now the font scaling is calculated for uniform 5mm text height for any screen resolution.
The fix will be in the next release (or earlier in the latest/edge version under Ubuntu)

**Comment by brunoherbelin** [comment]
Ok, font size and scaling is now robust. I think this issue can safely be closed.
