### ISSUE TITLE
Mapping parameters to mathematical functions (variable automation) 

### ISSUE THREAD

**Issue by Lorentz-Ipsum** [brunoherbelin/vimix#20]
I've played a bit with the program and what I've seen so far is awesome. But, coming from Resolume Arena, I felt there is some lacking functionality with respect the parameters.
I know Vimix doesn't have audio support yet, but maybe it would be possible to route some MIDI or audio so that, for example, the gamma slider changes with the volume or with the pitch.

For me, one of the best features of vj programs is the ability to have pulsating effects that sync with the music. 

On the most basic level I would like to be able to choose a tempo and then map a variable to a sine or cosine that oscillates at that tempo. 

I'm no programming expert, but I think with some guidance on how to start I could experiment with this, if it's plausible.

**Comment by brunoherbelin** [comment]
You are right that vimix is still in need for the synchronization mechanism with the audio.

This is planned in the [future plans](https://github.com/brunoherbelin/vimix/wiki/Future-plans):
- OSC control (network)
- MIDI control

it is a choice that vimix does not touch audio, but yes, tools to help VJ and DJ tols communicate should be implemented to help!
Stay tuned...

**Comment by MoorPoor** [comment]
talking of mapping parameters, that would be great to have this option as open as possible. 
For someone not using OSC nor MIDI a simple computer mic/linein to parameter mapping would be the best way to go.

think of the possibility to get values from lets say a webcam and map specific regions (changing in movement or brightness) to  trigger videos or paramters :O
something like this project... (hope its fine to share this link)
https://www.zachpoff.com/software/video-trigger/
Many thanks!

**Comment by brunoherbelin** [comment]
yes, with MIDI, you could use the video-trigger or any other tool you like.
Still need to implement the MIDI input in vimix though... :)
B.

**Comment by brunoherbelin** [comment]
Please check the [OSC](https://github.com/brunoherbelin/vimix/wiki/Open-Sound-Control-API) support and the [TouchOSC](https://github.com/brunoherbelin/vimix/wiki/TouchOSC-companion)'s layout. As [TouchOSC has a MIDI Bridge](https://hexler.net/touchosc-mk1) : this could work !
