### ISSUE TITLE
UI problems

### ISSUE THREAD

**Issue by OlegoroV** [brunoherbelin/vimix#26]
1. Every source creation resets current mixing circle position.

2. If main window is on big display (2560*1440) and floatable windows (output, player) are near to the right border of main window and I move main window to smaller display (FullHD), then all floatable windows appears out of main window and there is no way to move them inside.

**Comment by brunoherbelin** [comment]
*To answer to 1*

The idea was to make sure user sees where the source appears once created, but it was maybe a bit too intrusive! I improved by testing first if the created source is visible once created, and shift the view only if needed. This should fix your problem.

*To answer to 2*

Yeah, this is annoying but I am not fully convinced of having the best solution (from the user's standpoint). I could implement these:
- When a window is 'lost', hide and show it again; this tests if the window is out of view (outside application window) and shifts it slightly to make it visible again (but still in the position where the user placed it)
- do not allow to put the window out of sight; when the application window changes (e.g. resize), the windows are moved to ensure they are visible (but prevents user from placing the windows freely)

The first option is temporarily implemented (latest git) but I am not fully satisfied. Let me know if you can test it.

**Comment by OlegoroV** [comment]
Now both problems are solved for me! Thank You!!!

But I have more functionality requests for You =)

1. When a new source is created it is always placed in the same position. And it overlaps the first one. I don't sure that it can be fixed somehow, because program can't know where I want a new source place to. But I expect new source below previous one (I arrange sources in two columns at the left and right of mixing circle)

2. Often I can't recognize my sources by their thumbnails. Is it possible to add ability to show source's names (or filenames if name is not defined)? And maybe font size slider. Where text should be? Below picture, above or on picture? I don't know yet. Maybe add settings for it? And slider for thumbnails size.

**Comment by brunoherbelin** [comment]
Please checkout vimix 0.6.3 !

1. The source importation is still the same, but a new Align & distribute option allows to cleanup a selection
2. following your suggestion, source icons now have their initials to better identify them

Thanks for your constructive input!
