### ISSUE TITLE
Notes feature

### ISSUE THREAD

**Issue by OlegoroV** [brunoherbelin/vimix#27]
Can You, please, add window for Notes?

**Comment by brunoherbelin** [comment]
![20210510144050373_vmixcapture](https://user-images.githubusercontent.com/60393189/117660844-f0a10b80-b19d-11eb-950e-e637956cc41f.png)

**Comment by brunoherbelin** [comment]
NB: if you pin the note down (icon top corner), it stays fixed in this view. 
Overwise its is over all views.

**Comment by OlegoroV** [comment]
Thank You for this feature!
Sadly still no cyrillic support.

![image](https://user-images.githubusercontent.com/74917360/117717689-ceca7780-b1e3-11eb-9821-09d29406f526.png)

**Comment by brunoherbelin** [comment]
This is same as #25
Will see what I can do..
