### ISSUE TITLE
Advanced source settings

### ISSUE THREAD

**Issue by OlegoroV** [brunoherbelin/vimix#29]
Often I need to set the same settings for many sources (scale, position, brightness/contrast etc.)
Now I'm trying to move all sessions from GLMixer.
At this moment it's not possible to setup cources quick and precise.
Can You, please, add a toggable window with all settings represented with digits?
Thus this process could be as informative as in GLMixer and not overloading UI when setup is done.

**Comment by brunoherbelin** [comment]
Thanks for the feedback. I agree this is missing.

Two things that already answer your comments:
- To enter a value on a slider, CTRL+clic on it: you can now write down the value you want.
- I added copy/paste actions in a menu for the source Filters (latest source)

Working on the implementation of:
- Source Metrics (inside the metrics' corner window) to allow to see and enter values of the current source's alpha, scale, position & Angle.
- Linking mechanism for associating (and dynamically following) properties of sources (i.e. one source 'follows' the Filters of another).

Will let you know when you can test it and we can improve.

**Comment by OlegoroV** [comment]
CTRL+Click - nice feature. Will use it. Thank You.
Copy/paste everything - I think, sometimes will be helpful for me.
Source Metrics and Linking mechanism - very cool features!!! Will wait them!

**Comment by brunoherbelin** [comment]
Hey, you might want to test the following in version 0.6:

 - Metrics (enabled in Settings) : with 'Source' metrics, you see the current source geometry and can directly edit and enter values (with Ctrl+clic or double clic)
 - copy paste of Filter settings (new context menu icon)

The 'follow other sources settings' idea was tested but is not fully satisfying yet: i'll let you know
