### ISSUE TITLE
Where is control to send output to 2nd monitor/projector?

### ISSUE THREAD

**Issue by DarrellJonsson** [brunoherbelin/vimix#3]
Where is control to send output to 2nd monitor/projector?

**Comment by MoorPoor** [comment]
drag an drop the output window to your screen > double click will make it full screen.
You got two output windows. a small one for your working space, another one (may be behind other windows) as output... take this one!
This works for me using ubuntu 20.04

**Comment by brunoherbelin** [comment]
Thanks MoorPoor for your help ! :)

If this behavior is not optimal, let me know how you'd prefer it!

**Comment by brunoherbelin** [comment]
This question is answered and note has been taken improve selection of output fullscreen monitor in Issue #18

**Comment by linuxnow** [comment]
Just a quick question: can window decorations be removed from the output window? Something like when you press 'f" fo view in full screen video players. f could also be a way to maximae the output window.
