### ISSUE TITLE
Glfw error

### ISSUE THREAD

**Issue by OlegoroV** [brunoherbelin/vimix#31]
After I compiled vimix from source, I have an error when I start program from snap:

Error: Glfw Error 65544: Linux: Failed to watch for joystick connections in /dev/input: No space left on device

I press Close and program starts normally.

**Comment by brunoherbelin** [comment]
Hi Oleg
is this still doing it? 
I could not reproduce, so it's hard to detect...

**Comment by linuxnow** [comment]
Same error for me in Fedora 34
Error: Glfw Error 65544: Wayland: Failed to connect to display

**Comment by brunoherbelin** [comment]
If this error did not occur anymore after a year, I think I can safely close the issue... Let me know otherwise.
