### ISSUE TITLE
GPL-3.0-only or GPL-3.0-or-later?

### ISSUE THREAD

**Issue by TechnologyClassroom** [brunoherbelin/vimix#34]
I am adding a stub page for vimix to the [Free Software Directory](https://directory.fsf.org/wiki?title=Vimix) and I cannot tell if this project is GPL-3.0-only or GPL-3.0-or-later.  Can you answer which one it is?  The answer would usually go in the license header of source files or in the README file.  I could help with a pull request after I know which it is.

**Comment by brunoherbelin** [comment]
Hi
Thanks for the initiative.

The [LICENSE](https://github.com/brunoherbelin/vimix/blob/master/LICENSE) file specifies GPL 3.0

I didn't think further if it should be 3.0 only or 3.0 or later: your suggestions are welcome.
And yes, I did not have time (nor found the motivation) to add the licensing info on the header of each source files: if you were willing to help it would be greatly appreciated !

**Comment by TechnologyClassroom** [comment]
I would suggest GPL-3.0-or-later.  This ensures compatibility with future versions of the GPL.  I use `-or-later` on all of my GPL code.

Example: GPL-2.0-only and GPL-3.0-* are incompatible, but GPL-2.0-or-later is compatible with GPL-3.0-only and GPL-3.0-or-later.

**Comment by brunoherbelin** [comment]
Ok I see, and agree with you: I'd choose GPL-3.0-or-later
Thanks for the suggestion!

I updated the [README](https://github.com/brunoherbelin/vimix/blob/master/README.md)
Something else to change?

I'd gladly accept a pull-request if you'd be willing to help.

**Comment by TechnologyClassroom** [comment]
What you did is good enough for the most part.  If you want to go "all the way", there are a few extra things that can be done following the directions at the very end of the license to craft license headers.  A license header for Vimix might look like this (The copyright line would need some modifications, but the dates are correct):

```
# Vimix - Live video mixer
# **Copyright** (C) 2020-2021 Bruno Herbelin <bruno@email.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

This header could go on the README file (without # comments) and also near the top of all source files.  Placing it at the top of each source file is a lot of work, but it can be automated.  Not everyone does the source file headers, but it allows the license to be easily maintained in the future if a file is picked up by another project.

**Comment by prez** [comment]
Unnecessary. Take a look at how e.g. coreboot does it: https://github.com/coreboot/coreboot/blob/master/src/northbridge/intel/haswell/acpi.c#L1

**Comment by TechnologyClassroom** [comment]
Here is an example with the full headers: https://git.savannah.gnu.org/cgit/coreutils.git/tree/src/cat.c

**Comment by brunoherbelin** [comment]
Done !
