### ISSUE TITLE
New (old) features request

### ISSUE THREAD

**Issue by Ouyuegu** [brunoherbelin/vimix#36]
Hello!

After just migrating over to Vimix from GL Mixer, there's a few things I was using quite a lot and wondered if they might be featured in any upcoming versions...

They are:

• cursor options... specifically "Fuzzy cursor" which allows us to "jitter" the video positions.
• the ability to set a start and end point for a clip rather then having to right-click-drag a section to skip
• frame by frame navigation in player mode for fine-selecting loop points, etc...
• png masks
• "Loopback" source

I have been really impressed by Vimix, and love its interface, and general look and design. I understand that some of the requests above might be antithetical to some of your design principles, but as I said, just wondered if there was a plan to reinstate/reintroduce any of these features we found so useful.

Many, many thanks in advance!

**Comment by brunoherbelin** [comment]
Thanks for your input and support !
The goal is indeed to keep the best of GLmixer, so your comments are very appreciated.

• cursor options... specifically "Fuzzy cursor" which allows us to "jitter" the video positions.
> I didn't think it was used, so I only kept the 'smooth cursor' (in settings now). But yeah, I love the concept and will think of restoring this feature !!

• the ability to set a start and end point for a clip rather then having to right-click-drag a section to skip
> as I'm currently working on improving the UI of the timeline, I'd welcome your specific suggestions: the vimix 'cut' tool is more powerful than before (so you can do the same as before) but maybe it is the tools to do it that are not optimal?

• frame by frame navigation in player mode for fine-selecting loop points, etc...
It is available in the player, 

• png masks
its a pending feature :): the mask painting (Texturing View) allows drawing by hand, and it was thought that loading an image could be done. Will push it higher in the TODO list..

• "Loopback" source
Its now called 'rendering output' source: + new source, 'internal'

**Comment by Ouyuegu** [comment]
Thank you for your responses! Really looking forward to some of these features to come back... and for 6.1 to come out so I can finally upgrade from 5.4...

Here are some further clarifications on our requests.

> • the ability to set a start and end point for a clip rather then having to right-click-drag a section to skip
> as I'm currently working on improving the UI of the timeline, I'd welcome your specific suggestions: the vimix 'cut' tool is more powerful than before (so you can do the same as before) but maybe it is the tools to do it that are not optimal?

Specifically, I guess it would be nice to be able to use the arrow keys on the keyboard to step through frames, and then keyboard shortcuts to select in and out points? Using the right-click thing is a bit awkward on a trackpad, and also at the moment, there's a weird bug where for some clips, it always skips to the last frame of the video even if it's been skipped... so it plays to the end, gets to the "skip" section, and instead of then reversing, or going back to the beginning, first platys one or two frames from the end of the video...

> • frame by frame navigation in player mode for fine-selecting loop points, etc...
> It is available in the player,

Maybe I missed this? Can you use the keyboard to navigate like I said above?

Thanks in advance!

**Comment by Ouyuegu** [comment]
Ah... I have one more that we discovered yesterday...

We want there to be an easy way to one-click show a clip _and_ start it from the beginning simultaneously... currently, it seems this is only possibly with a newly-imported and not-yet-played clip... as it automatically starts playing when it is moved into the playing area. 

Or am I missing something?

**Comment by brunoherbelin** [comment]
Thanks  Ouyuegu : yes the re-start on un-suspend feature was in GLMixer and will re-implement this soon !

Are you under Linux or OSX?

**Comment by Ouyuegu** [comment]
I'm on OSX. Still running the penultimate release of Vimix due to our previous experience not being able to get the new one running.
