### ISSUE TITLE
Add session folder error- Mac OS X 12.0.1

### ISSUE THREAD

**Issue by Ouyuegu** [brunoherbelin/vimix#41]
We have spotted an error when using Vimix 6.2 on Mac 12.1.

When we try to add a folder in the "Session" drop down box, it will flash up the message "busy- close file dialog box to resume" for a millisecond, and then not bring up the file dialog box where I would be able to select my folder.

I have tested this function on OSX 11.4, and it works fine. This error only occurs, to my knowledge, on our computer running OS X 12.0.1.

**Comment by brunoherbelin** [comment]
Please try Release 0.6.3
I've updated the filedialog library and hopefully it will support latest OSX
Let me know ! (I do not have a machine with OSX 12 to test...)

**Comment by Ouyuegu** [comment]
Hello there!

So sorry this took so long to get back to you about... I have downloaded 0.6.3, and tested it on Mac OS X 12.1, but it still does not work.

Here's what happens:


https://user-images.githubusercontent.com/38443695/153115106-56eb8659-ce4c-491e-bf8d-b5f60909f493.mp4

**Comment by Ouyuegu** [comment]
UPDATE: An unconnected issue flagged that the hard disk on which we were using VIMIX was corrupt in some way, and when we reinstalled the system, this error stopped occurring.

So, I guess I can say that this issue is fixed.

Thanks for your help!
