### ISSUE TITLE
finetune chroma- & Lumakey

### ISSUE THREAD

**Issue by MoorPoor** [brunoherbelin/vimix#44]
I'm so glad to see that this project continues to evolve! Thanks a lot for this. especially for the Linux users among us it is a great enrichment!

To the point. I would be very happy about the possibility of being able to fine-tune the chroma- or Lumakey.
a second parameter to smooth the edges for a smoother transition.
options like that can be found in OBS or kdenlive as example
This would be essential, especially in video material with color areas that are not clearly separated.

Many thanks!

**Comment by brunoherbelin** [comment]
Please check vimix 0.7.1 : the chroma-key filter is now improved 

You now have to do 'clone and filter' of a source to access to the list of advanced filters.

+ If you want a very specific chroma keying algorithm, you can even develop your custom shader

**Comment by brunoherbelin** [comment]
Plse check the new doc for chromakeying : https://github.com/brunoherbelin/vimix/wiki/Filters-and-ShaderToy#alpha
