### ISSUE TITLE
OSC message /vimix/current/sync

### ISSUE THREAD

**Issue by lupin3rd** [brunoherbelin/vimix#49]
Hi at all,
i'm using this message to sync my puredata patches with vimix. I think that will be usefull to have also the name attribute in the reply and not only alpha attribute.
Actually index attribute change very often (example: i remove a video) and if i want to communicate with my video i use always name attribute in OSC message... then i always receive a list of index and alpha...and if i want name attribute i need to cycle all index with a OSC request...

I think that sync response need to contain "name" to reduce OSC message :-)

Thank you very much!

**Comment by brunoherbelin** [comment]
Yeah, sure, happy to adapt to the needs!

I see two easy alternatives.

1. send one more line as response to `/vimix/current/sync`

    /vimix/current/0 f { 1.0 if current, 0.0 otherwise }
    /vimix/0/alpha f { alpha value of source 0 }
    /vimix/sourcename/alpha f { alpha value of source 0 }
    ... 
    etc., for as many source currently available in vimix

2. Implement response to `/vimix/sourcename/sync` request

    /vimix/srcname/current  f { 1.0 if current, 0.0 otherwise }
    /vimix/srcname/lock  f { 1.0 if locked, 0.0 otherwise }
    /vimix/srcname/play  f { 1.0 if playing, 0.0 otherwise }
    /vimix/srcname/depth f { depth value }
    /vimix/srcname/alpha f { alpha value }

Let me know what would be more appropriate (or if both should be implemented)

**Comment by lupin3rd** [comment]
Hi Bruno,
i think that the first solution is very good to have base information immediately...
but why not:
      /vimix/current/0 f { 1.0 if current, 0.0 otherwise }
      /vimix/0/alpha f { alpha value of source 0 }
      /vimix/0/sourcename s { string with name of source 0 }
      ... 

I think that it's very usefull also implement response to /vimix/sourcename/sync request.

**Comment by brunoherbelin** [comment]
Perfect as you propose and implemented !
Documentation updated https://github.com/brunoherbelin/vimix/wiki/Open-Sound-Control-API 

The change is available if you pull last version of code on git and recompile, or with the latest/edge version of linux snap. Will be in next release.

**Comment by lupin3rd** [comment]
Hi Bruno,
i write a PureData patch to sync sources by OSC and works fine! thank you!

Can you also implement response to /vimix/sourcename/sync request ?

**Comment by brunoherbelin** [comment]
Thanks, all your requests make lots of sense and were implemented (same, in code and edge version)

Question: would you be interested in a submission to NIME https://www.nime.org/ ? We could continue this discussion on a private channel..

**Comment by brunoherbelin** [comment]
Thanks, all your requests make lots of sense and were implemented (same, in code and edge version)

Question: would you be interested in a submission to NIME https://www.nime.org/ ? We could continue this discussion on a private channel..

**Comment by lupin3rd** [comment]
We can use NIME forum to continue discussion?

**Comment by brunoherbelin** [comment]
or [Discord](https://discord.gg/XZbNmRPe) ?

**Comment by brunoherbelin** [comment]
implemented in dd92f2dccbffd751feddcd95cd3fc9444822f308
