### ISSUE TITLE
Image sequence feature not working

### ISSUE THREAD

**Issue by Ouyuegu** [brunoherbelin/vimix#50]
Hey there!

Just upgraded to latest version (0.7) using Mac OS 11.6.8.

Image sequence feature isn't working, basically, and I get this readout:

> 0001  MultiFileSequence '' invalid.
> 0002  MultiFileRecorder creating video 113 x 197 : 3.
> 0003  MultiFileRecorder could not include images /Users/adamcasciaro_1/Desktop/Useful Images/Unhappy.png.
> 0004  MultiFileRecorder could not include images /Users/adamcasciaro_1/Desktop/Useful Images/Kagan Book.png.
> 0005   Warning - MultiFileRecorder: Failed to close recording.
> 0006   Image sequence saved to /Users/adamcasciaro_1/Desktop/Useful Images/_sequence.mov.
> 0007   Warning - 'file:///Users/adamcasciaro_1/Desktop/Useful%20Images/_sequence.mov': Stream contains no data.
> 0008   Warning - MediaPlayer 487242179809690 Loading cancelled

Any ideas what i'm doing wrong, or if this is a known bug?

Many thanks!

**Comment by brunoherbelin** [comment]
Hey! 
Thanks for the bug report: you face a normal limitation of the process, but i am sorry that vimix is not giving you a more informative message. I will make the logs and dialog messages more clear.

The action 'Make a video' from a set of images only works if **all images are of the same size**. It uses the resolution of the first image in the list to create the video (eg. 113x197 pixels) and all other images are expected to be the same size. 

NB: An alternative would be to accept any image size but then users will also want to select the mode of size adjustment (resize, crop, center, etc.) and if felt as this goes beyond the purpose of the feature. But your suggestions are welcome.

**Comment by brunoherbelin** [comment]
There was indeed a problem with invalid height (odd number) that is now fixed in 3c32f1da6e002362edda9b5b70d10690dd4e1a09. There are also more checks and hopefully more clear error messages.
