### ISSUE TITLE
Separate commands for xy OSC inputs 

### ISSUE THREAD

**Issue by aquaresima** [brunoherbelin/vimix#52]
Hello,

I am new to Vimix, VJ, OSC and everything.
But the simplicity with which I could set it up is impressive and for this I am thankful, and I would like to keep playing.

One feature I would like is to separate the `position` OSC controller - and all those that have `ff` inputs to independent values:
 `/vimix/current/position ff 0.1 0.2` 
 ->  
 ```
 /vimix/current/positionx f 0.1
 /vimix/current/positiony f 0.2 
```

Indeed, it seemed to me, that many free OSC controller for Android do not support the double value format. `/vimix/xycommand ff 0.1 0.2` 

Would that be possible?
Is it any workaround for my free OSC App otherwise?

Thanks a lot,
Ale

**Comment by brunoherbelin** [comment]
The correct way to do this with OSC is to use the 'NIL' value type.
When sending a pair of floats in OSC, the list of arguments is `ff` and followed by two values; if one `f` is replaced by `N`, no value is expected at this place. Your example would then be:

```
/vimix/current/position fN 0.1
/vimix/current/position Nf 0.1
```

[Documentation](https://github.com/brunoherbelin/vimix/wiki/Open-Sound-Control-API) was updated accordingly.

This is now available in source code 5a6daf79b6f24d3df936c48439336d4c23e00a6a and will soon be packaged.

**Comment by brunoherbelin** [comment]
Of note: you may also find ways to adapt to the OSC messages sent by an Android app using the [OSC translation in vimix](https://github.com/brunoherbelin/vimix/wiki/Open-Sound-Control-API#automatic-translation).

**Comment by brunoherbelin** [comment]
Thank you for confirming if this issue was resolved.
