### ISSUE TITLE
Cant broadcast over srt

### ISSUE THREAD

**Issue by felixgonsug** [brunoherbelin/vimix#53]
When pressing over stream, only "share over local network" option is available. There is no option to stream over srt.

The logs shows the following when i press over the stream option in the output winow:
`ERROR          x264enc gstx264enc.c:163:load_x264: failed to load '/usr/lib/x86_64-linux-gnu/x264-10bit/libx264.so.152'`

Im in Ubuntu 20.04, vimix 0.7.1 from snap and libx264-155 is installed (not libx264-152).

Any idea how to solve this?

**Comment by brunoherbelin** [comment]
Sorry that the snapping core has messed-up dependencies : nothing that the vimix code can solve.

I encourage you to compile vimix from source: its in fact not difficult even if you are not used to it (and fairly easy if you have experience). See the [README](https://github.com/brunoherbelin/vimix/blob/master/README.md).

Still, I will investigate and file a report to snap (its a problem of wrong versions of dependencies for gstreamer package in the snap).

**Comment by felixgonsug** [comment]
Ok, thanks for the quick response, i'll try compiling.

**Comment by felixgonsug** [comment]
Just a sugestion, it ould be nice to have a flatpak version. After compiling, i'll try to add that option and make a PR

**Comment by brunoherbelin** [comment]
Yes, the flatpak option was a good suggestion.
if you are impatient and can't wait for vimix to be listed in flathub, you can make a flatpak for yourself: 
https://github.com/brunoherbelin/vimix/tree/master/flatpak

The flatpak does include all dependencies and can stream SRT.
