### ISSUE TITLE
no element "srtsrc"

### ISSUE THREAD

**Issue by polymorphicengine** [brunoherbelin/vimix#55]
I followed the instructions to stream from my phone camera (i tried both the haivision app and the Larix one)

But when i click on 'Call' the following error pops up:

```
0001   Creating Source SRT receiving from 'srt://192.168.0.52:7071'
0002   Warning - Stream 666707685247506099 Could not create stream: no element "srtsrc".
```

I compiled vimix from source with the latest updates. I'm sure 192.168.0.52 is the local IP of my phone..

**Comment by brunoherbelin** [comment]
Could you try to install the GStreamer Bad Plug-ins package ?

**Comment by polymorphicengine** [comment]
Do i have to compile again after installation?

**Comment by brunoherbelin** [comment]
Sorry for the late answer: I don't think you need to recompile if you compiled vimix yourself, but I never tried, so your input on this is welcome! 
If you are using the snap under Linux, then indeed SRT is not included. I am working on a flatpak that would add SRT in the package.

**Comment by brunoherbelin** [comment]
Further developments with flatpak should have fixed the problem.
For now, check how to generate the flatpak package in the [README](https://github.com/brunoherbelin/vimix/blob/master/README.md#generate-flatpak)
Hopefully soon, vimix will also be in the Flathub repo of linux app (the SRT dependency being fixed)
