### ISSUE TITLE
Screen Capture failed to initialize

### ISSUE THREAD

**Issue by nzoschke** [brunoherbelin/vimix#57]
On 0.7.1 on OS X, screen capture always goes `loading...` then warning popup with `Failed to initialize`.

Full logs:

```
0050  Device Screen capture selected its optimal config: video/x-raw BGRA 3024x1964@30.0fps
0051  Stream 1232612263997249 Opened 'avfvideosrc capture-screen=true ! video/x-raw,format=BGRA,framerate=30/1,width=3024,height=1964 ! videoconvert ! video/x-raw,format=RGB ! queue max-size-buffers=3 ! videoconvert ! appsink name=sink' (3024 x 1964)
0052   Warning - Stream 1232612263997249 Failed to initialize.
```

I'm hoping to capture the screen from another program, [projectM visualizer](https://github.com/projectM-visualizer/projectm) to layer in as an audio reactive element.

**Comment by nzoschke** [comment]
Very impressive project BTW!

**Comment by brunoherbelin** [comment]
Thanks!

This is very probably the same problem than in  #58: 
The shared lib used for access to screen capture in OSX is a gstreamer plugin using AV Foundation (https://developer.apple.com/av-foundation/) ; it might require specific support for M1/M2 new architectures. 

You are right to try to compile vimix for M1 specifically; let's see how this goes in #58 !

**Comment by nzoschke** [comment]
I did have luck building on M1 on https://github.com/brunoherbelin/vimix/issues/58! H

However then I get a new error:

Add Source -> Connected -> Select Stream

```
0001  Refusing stream requests to vimix@studio.attlocal.net.0. No streaming ongoing.
0002  Metronome Ableton Link Enabled
0003  Metronome Ableton Link start & stop sync Enabled
0004  No GPU decoding plugin found.
0005  OSC: Loaded 1 translation.
0006  OSC: Listening to UDP messages sent to 192.168.1.161:7000
0007  Font size 20
0008  New session ready.
0009   Session '' loaded with no source.
0010   Warning - DeviceSource Could not construct test pipeline avfvideosrc capture-screen=true name=devsrc ! fakesink name=sink:
no element "avfvideosrc"
```

**Comment by nzoschke** [comment]
Google sounds like more build or gstreamer quirks...

- https://gstreamer.freedesktop.org/documentation/applemedia/avfvideosrc.html?gi-language=c
- https://stackoverflow.com/questions/64073844/no-element-avfvideosrc-in-gstreamer
- https://stackoverflow.com/questions/66296668/gstreamer-macos-big-sur-camera-input

**Comment by nzoschke** [comment]
I'm trying to install gstreamer via https://gstreamer.freedesktop.org/documentation/installing/on-mac-osx.html?gi-language=c#

But not yet getting it wired up...

**Comment by nzoschke** [comment]
Maybe I need to wire this through

https://gstreamer.freedesktop.org/documentation/installing/on-mac-osx.html?gi-language=c#manual-compilation-with-pkgconfig

**Comment by nzoschke** [comment]
Hm I went back to homebrew gstreamer since things are building there. I also see it working on its own with

```
brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav gst-rtsp-server gst-editing-services gst-devtools
gst-launch-1.0 videotestsrc ! autovideosink
```

But still vimix has the warning:

```
0011   Warning - Stream 1313492662361541 Could not create stream: no element "videotestsrc".
```

**Comment by brunoherbelin** [comment]
wouah! nice job 
yes agreed: to avoid recompiling gst: it's a beast! BUT: afvideo from OSX is not included... So what I do is compile only gst plug-ins bad from the g streamer installed with brew.

I will send you more info tonight

**Comment by nzoschke** [comment]
Going to close this in favor of https://github.com/brunoherbelin/vimix/issues/58
