### ISSUE TITLE
What features exist and are planned?

### ISSUE THREAD

**Issue by lukors** [brunoherbelin/vimix#6]
I've been unable to find a list anywhere of implemented and planned features.

Maybe there also are some things in GLMixer that you want to do differently in vimix?

This type of information would be useful to me. :)

Thanks a lot for making these applications!

**Comment by brunoherbelin** [comment]
Please check the [wiki](https://github.com/brunoherbelin/vimix/wiki) !

**Comment by lukors** [comment]
That'll do it, thanks! :)
