### ISSUE TITLE
vimix not using 

### ISSUE THREAD

**Issue by MoorPoor** [brunoherbelin/vimix#60]
Hei!
happy to see, that so much happend here! Thanks!
after wondering that "undo" and "redo" keys are not working, i noticed that vimix is not using the system language keyboard layout  for me on ubuntu 22.10, can this be changed?

thanks a lot!

**Comment by brunoherbelin** [comment]
aha... you mean you press a key and another one is recognized?
e.g. in AZERTY French layout, W and Z are inverted : so CTRL+W would do CRTL+Z ?

I don't know why glfw and imgui would not do that automarically... i will check

**Comment by brunoherbelin** [comment]
So indeed, imgui and glfw do not provide easy support for different keyboard layouts. 

I made a quick hack that should be satisfying for most Latin keyboard layouts in 5f68f516938d19f99e63d5ba5f2a630e29bb1830
(NB need to rebuild vimix to test: will be in next release)

**Comment by MoorPoor** [comment]
cool! thanks a lot!
