### ISSUE TITLE
flatpack display environment variable missing

### ISSUE THREAD

**Issue by polymorphicengine** [brunoherbelin/vimix#61]
Hello Bruno!
Thanks for all your great work! 
I just tried running vimix with flatpack, as you described in the README and it installed fine and appears when i run `flatpak list`, but once I run `flatpak run io.github.brunoherbelin.Vimix` I get the following error:

```
Glfw Error 65544: X11: The DISPLAY environment variable is missing
Failed to Initialize GLFW.
```
if I do `echo $DISPLAY` it returns `:0`, I tried looking for a solution online but couldn't really find anything helpful..

best,
Martin

**Comment by brunoherbelin** [comment]
Thanks for being beta-tested of this latest developments :) !

Indeed, there was a problem that I didn't realize before (Wayland vs. X11): it should be fixed now.

Please try again (restart at step 'Get the flatpak manifest for vimix:')

**Comment by polymorphicengine** [comment]
Yes, all good now! And the solution with the loopback camera works perfectly for my usecase with hydra!! 
Thanks a lot!!

**Comment by brunoherbelin** [comment]
Great then!
