### ISSUE TITLE
Bounce loop mode bug

### ISSUE THREAD

**Issue by lupin3rd** [brunoherbelin/vimix#68]
Seem that the bounce loop on video player don't works... when the video reverse it jump at start...
I upload a video to explain:
https://youtu.be/8SzNcaCVWEE

**Comment by brunoherbelin** [comment]
Thanks for the bug report. 

It is however a gstreamer bug, which is most often related to the hardware decoding drivers. 
To avoid the problem this hardware decoding reverse playing problem, vimix offers to force to disable the hardware decoding for a given video (not as a general setting): 

![Screenshot from 2023-03-06 23-27-59](https://user-images.githubusercontent.com/60393189/223260361-589dd818-ff16-4e28-9abb-ab71a1dfba38.png)

Could you please indicate which hardware decoding is used for your problematic video, and most importantly if you still have the bug with pure software decoding (i.e. after disabled hardware decoding for this video).


NOTA BENE: I am thinking of a new feature for vimix that would load the sequence of images in RAM (or betterm in GPU RAM), thus allowing all crazy playback speeds, randomization, reversing, etc. I am thinking of calling this 'video clips'. However, the problem remains on how to initially populate this sequence of images; was thinking of a special selection area in the timeline of a video? Any suggestion?

**Comment by lupin3rd** [comment]
This is the log when i use this video:
0001  MediaPlayer 678227252327804525 Opened 'labbra.mp4' (H.264 (Baseline Profile), ISO MP4/M4A 1920 x 1080)
0002  MediaPlayer 678227252327804525 Timeline [0 107966877777] 3239 frames, 0 gaps
0003  MediaPlayer 678227252327804525 Uses nvh264dec decoding and OpenGL PBO texturing.
0004  Source 'labbra' linked to Media 678227252327804525.
0005   Added Video File source 'labbra' (labbra.mp4 H.264, 1920 x 1080, 30fps)

If i disable hardware decoding the video works fine.

I'm thinking about "video clips"... I think that a solution can be a selection on the timeline that create a new "video clip" source.

**Comment by brunoherbelin** [comment]
> If i disable hardware decoding the video works fine.

Great, then at least you can work !

>  0003 MediaPlayer 678227252327804525 Uses nvh264dec decoding and OpenGL PBO texturing.

exactly ; it was the same for me (thus the 'fix' above). 
It seems to not be a problem anymore with the latest nvidia drivers 515... or maybe its just that some videos are encoded differently... very hard to know, and different on each machine... 

That said, switching to 'software' decoder is a solution and it would be nice to have a way for the user to discover it when encountering a problem: we can do a Q&A in the wiki ? Or in the vimix inside help? Or a log info line saying 'if this decoding is causing problems in playback, revert to software decoding' ?

**Comment by lupin3rd** [comment]
I think that a Q&A in the wiki is good :-)

**Comment by lupin3rd** [comment]
Problem solved.
