### ISSUE TITLE
UI Rendering broken

### ISSUE THREAD

**Issue by Francis148** [brunoherbelin/vimix#8]
Since rougly a week, UI rendering is broken: after starting vimix, I only see a black screen and if I open my application launcher, I can see this:
![vimix problem](https://user-images.githubusercontent.com/72497251/95317221-28a54080-0895-11eb-84d5-405ce5a8d524.jpg)

There seems to be no logfile and there are no error messages in the terminal.
I'm using intel hd graphics with mesa 20.1.8

**Comment by brunoherbelin** [comment]
Thanks for the feedback. Its apparently a font display issue, and no error is produced (no message or logs to check)

If not already the case, please try with the latest/edge package from Snapstore (0.3 from 8/10/2020). 
If the problem persists with latest version, it would therefore be an OpenGL driver issue; thanks for posting the glxinfo ($glxinfo > infogl.txt)

**Comment by Francis148** [comment]
I'm compiling latest git, so here is the glxinfo:
[infogl.txt](https://github.com/brunoherbelin/vimix/files/5351030/infogl.txt)

**Comment by brunoherbelin** [comment]
Very strange :(
Your opengl seems ok, and anyway the font rendering does not use anything fancy!

I know its a bit annoying to do, but as you use git, could you please go back to the last commit before it breaks? I have no way to reproduce your problem (no computer with intel HD drivers) and never had the issue. Sometime late sept when it still worked ? (https://github.com/brunoherbelin/vimix/commits/master)

Thanks, and sorry for the bug :(

**Comment by Francis148** [comment]
No problem, those things happen and since vimix is still compiling rather quickly, it was doable.
First buggy revision: 688aee8831719ae9dd0ec2092532f2ebb5e9d4e5 (Fixed resolution issue with different monitor DPI)

**Comment by brunoherbelin** [comment]
Thanks !! Ok, I think i get the problem with the font display!
Please try again with revision > 31ebccd in Master branch (latest to date).

**Comment by Francis148** [comment]
Font rendering is fixed, thank you!
The UI rendering is slightly off, though: the "Enter fullscreen" button and OpenGL text at the bottom are cut off:
Native resolution 3200x1800, global scale of 250%:
![3200x1800, 250% scale](https://user-images.githubusercontent.com/72497251/95656088-2ef12200-0b0c-11eb-96bf-5ba9b01fa4d1.jpg)

Native resolution 3200x1800, global scale of 100%:
![3200x1800, 100% scaling](https://user-images.githubusercontent.com/72497251/95656098-3ca6a780-0b0c-11eb-9c07-657f52f19c8f.jpg)

Reduced resolution of 1920x1080, global scale of 100%:
![1920x1080, 100% scaling](https://user-images.githubusercontent.com/72497251/95656111-58aa4900-0b0c-11eb-9568-9255ef3d190e.jpg)

**Comment by brunoherbelin** [comment]
Great! Thanks for pointing this out; I would have missed it otherwise..

When you say 'global scale', you mean the Display seetings with Fractional Scaling under Ubuntu ?

**Comment by Francis148** [comment]
While I'm not using Ubuntu, I guess it is the same thing: scaling UI elements on HiDpi displays so they get bigger. You can see that the top bar is larger in the first image.
Looking at the images again, I think the high resolution is causing this issue, the scale is not the problem.

**Comment by brunoherbelin** [comment]
HiDPI scaling is a feature coming in multiple platforms and distribs, so it should not be entirely discarded. I'll check on my side; it shouldn't be too complicated.
Anyways, this is another issue, so I'm closing this one! Thanks the the help.
