### ISSUE TITLE
Program stops if I select a display with selection frame on F5 screen

### ISSUE THREAD

**Issue by flowerhorse** [brunoherbelin/vimix#86]
Maybe a bug:
Whenever I want to select an output screen with the blue selection frame, the program shuts down as soon as the selection has covered the entire output area. This is true for all screens displayed on F5.

**Comment by brunoherbelin** [comment]
Thanks! 

bug is fixed  in beta branch - https://github.com/brunoherbelin/vimix/commit/364ffc4659e6d9604ef451134e0e5233cb218515
