### ISSUE TITLE
cannot install on Ubuntu 23.04

### ISSUE THREAD

**Issue by skillz-xx** [brunoherbelin/vimix#90]
hello

seems like gnome 43 is desired, whereas the latest Ubuntu ships with gnome 44.

> 
(error: The application io.github.brunoherbelin.Vimix/x86_64/stable requires the runtime org.gnome.Platform/x86_64/43 which is not installed)

please help/fixit

thanks

**Comment by brunoherbelin** [comment]
I just released a new [Snap](https://snapcraft.io/vimix) (with Core22 and Gnome 42) : please let me know if it worked.
Alternatively, you can install the [Flatpak](https://flathub.org/apps/io.github.brunoherbelin.Vimix).

**Comment by brunoherbelin** [comment]
I upgraded to Ubuntu 23.04 and could install vimix from Ubuntu package and Snap.
Please confirm or provide more details.

**Comment by skillz-xx** [comment]
hello! yes it works for me in 23.04 too. thanks!
