### ISSUE TITLE
Adjustment of font on menus.

### ISSUE THREAD

**Issue by DarrellJonsson** [brunoherbelin/vimix#93]
Even on a 22 inch screen Vimix menu fonts appear too small.
How  can font size be adjusted in Vimix menus?

NOTE: Vimix 0.8.0 edge

**Comment by brunoherbelin** [comment]
There is a scale option in the Settings panel:

<img width="616" alt="Screenshot 2023-05-12 at 19 31 18" src="https://github.com/brunoherbelin/vimix/assets/60393189/ef6dd014-2b21-43ae-858b-833a7cb86c12">

Glad that you are trying vimix! Things are a bit different than with GLMixer, but all the features are there, plus of course more as it was re-designed to allow more flexibility.
