### ISSUE TITLE
Stutter in plaback when play speed adjusted

### ISSUE THREAD

**Issue by RKelln** [brunoherbelin/vimix#96]
Noticing that when I adjust the playspeed the playback pauses/stutters briefly. If I do something similar in `mpv` it seems fine. Is there a way to prevent stutter, it makes nudging the speed faster nearly impossible if you're trying to sync to music.

Thanks!

**Comment by brunoherbelin** [comment]
I agree that changing the playback speed should not cause pause, and I do not experience this when changing speed on the player. 

Could you please be more specific (i.e. which control do you do to change speed? from which value to what other value? etc.). Maybe a video recording of the vimix UI showing the problem could also help clarifying the situation. Thanks

**Comment by RKelln** [comment]
Was experiencing both with new OSC speed/ control in my pull request and the slider on the Player window, it isn't perfectly consistent but almost every time any adjustment to speed is made.

Videos recorded from two different machines, one from your flatpak build on the intel vaapi machine, one from my personal build on a nvidia gpu, both hardware enabled, both experience the stutter.
https://drive.google.com/drive/folders/11oQXPNpxX6krMDb2bOiQvzDv3zteW6Ax?usp=share_link

**Comment by RKelln** [comment]
Thanks, confirmed fixed!
