### ISSUE TITLE
Frei0r support

### ISSUE THREAD

**Issue by lupin3rd** [brunoherbelin/vimix#97]
Yesterday Dyne released Frei0r 2.3:
https://github.com/dyne/frei0r/releases
Frei0r is an updated, free and multiplatform collection of video effect. It could be nice if vimix add frei0r support :-)

**Comment by brunoherbelin** [comment]
Hey !
Frei0r is already embedded, used in some generated patterns.
So indeed, a filter that allows selecting a frei0r filter should be doable; I'll investigate.

**Comment by brunoherbelin** [comment]
It is now possible to add a gstreamer video effect into the pipeline that plays a video file.
Please try in vimix Beta 57154e5d0b74fc54829b64e629c2370f644db912 

Any gstreamer video effects can be used, including all the [Frei0r plugins.](https://gstreamer.freedesktop.org/documentation/frei0r)

The options 'Gstreamer effect' is available in the 'Timeline' menu of the Player window in vimix;

![image](https://github.com/brunoherbelin/vimix/assets/60393189/d427c89a-9a54-454b-a525-772a5ae75a89)
