### ISSUE TITLE
Order of sources is not saved

### ISSUE THREAD

**Issue by RKelln** [brunoherbelin/vimix#99]
Hi Bruno, I found another really bad bug for my show, the order of the sources is not preserved, so when I use a bank of midi fader controllers routed to osc to `/vimix/0/alpha` (0..7) say, which source is in 0 is not something I can control easily between loading of mixes. If I drag to change the order it controls the sources in proper order but that order is not preserved when I save the mix. 

Is this something you could fix asap? I'll have to rethink how I'm  doing one of the pieces otherwise. Maybe have to rename everything to the same thing in each mix to preserve order and use `/vimix/srcname/alpha', oof.

I'll look into this a bit more to see if I can figure out more details, but thought I'd start the bug since it's time sensitive (show is in 2 days).

**Comment by brunoherbelin** [comment]
Incredible that vimix could have been that wrong for so long... Thanks for pointing this out !

So, as it appeared, vimix was saving in the reverse order, so everytime you save and reload, it was swapping order...
There was another more subtle issue with ordering of clones, but that's also fixed now.

Anyways, please try in Beta a6b1d09ff1a409b4a2b6e57d29b6c80fb453925e and let me know.

**Comment by RKelln** [comment]
Thanks, [concert](https://www.ryankelln.com/project/transmigrations/) was last night and went well thanks to Vimix, although I had to hand edit the mix files to order sources and then not save them again, lol, but being able to hand edit was a life saver, text editable save files ftw.

Will confirm sometime this week.

**Comment by brunoherbelin** [comment]
Congrats for the concert!! Looks amazing! 
Interesting that you use Godot for generating graphics: we could think of a shared memory link to vimix :)
